services:
  - type: worker
    name: celery-worker
    region: ohio
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery --app app.core.worker.app worker worker --loglevel info --concurrency 4"
    autoDeploy: false
    envVars:
      - key: CELERY_BROKER_URL
        fromService:
          name: celery-redis
          type: redis
          property: connectionString
  - type: web
    name: app
    region: ohio
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    autoDeploy: false
    envVars:
      - key: CELERY_BROKER_URL
        fromService:
          name: celery-redis
          type: redis
          property: connectionString
  # - type: web
  #   name: flower
  #   region: ohio
  #   plan: free
  #   runtime: python
  #   buildCommand: "pip install -r requirements.txt"
  #   startCommand: "celery flower --app tasks --loglevel info"
  #   autoDeploy: false
  #   envVars:
  #     - key: CELERY_BROKER_URL
  #       fromService:
  #         type: redis
  #         name: celery-redis
  #         property: connectionString
  - type: redis
    name: celery-redis
    region: ohio
    plan: free # we choose a plan with persistence to ensure tasks are not lost upon restart
    maxmemoryPolicy: lru # recommended policy for queues
    ipAllowList: [] # only allow internal connections